### ISSUE TITLE
Support for transformer-only pipelines

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-converter#11]
Based on https://github.com/jpmml/jpmml-sklearn/issues/86

At the moment it's impossible to generate transformer-only pipelines, because the `ModelEncoder#encodePMML(Model)` method applies a set of visitors that clean the soon-to-be-generated PMML document from all unused preprocessing instructions:
https://github.com/jpmml/jpmml-converter/blob/master/src/main/java/org/jpmml/converter/ModelEncoder.java#L53-L56

Possible solution: class `ModelEncoder` should provide a "transformer-only" conversion mode.

**Comment by vruusmann** [comment]
Related to https://github.com/jpmml/jpmml-evaluator/issues/96

In other words, there should be an API for producing transformer-only PMML documents, and then consuming them.

**Comment by wunderbarr** [comment]
Hello,
When could we expect this "transformer-only" conversion mode? 
And our team is looking forward to this mode :) 
Moreover, if it is possible, a full example could be provided first before this mode, e.g for PCA. 
Because I am not familiar with PMML file, it is difficult and confusing for me to adjust relevant configuration as your suggestion in [Support for transformer-only pipelines](https://github.com/jpmml/jpmml-sklearn/issues/86).
Thank you!

**Comment by sin-en-2009** [comment]
Hello,
When could we expect this "transformer-only" conversion mode?
And my team is looking forward to this mode :)
I am not familiar with PMML file, it is difficult and confusing for me to adjust relevant configuration as your suggestion in Support for transformer-only pipelines.
And how do I look at the results of the data transformation, which is what the data looks like before I put it into the evaluator?
Thank you!
